# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from member import member_pb2 as member_dot_member__pb2


class MemberSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterUserMember = channel.unary_unary(
        '/member.MemberSrv/RegisterUserMember',
        request_serializer=member_dot_member__pb2.Member.SerializeToString,
        response_deserializer=member_dot_member__pb2.Member.FromString,
        )
    self.GetMyCustomerOpenOrderList = channel.unary_unary(
        '/member.MemberSrv/GetMyCustomerOpenOrderList',
        request_serializer=member_dot_member__pb2.MyCustomerOrderRequest.SerializeToString,
        response_deserializer=member_dot_member__pb2.MyCustomerOrderReply.FromString,
        )


class MemberSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RegisterUserMember(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyCustomerOpenOrderList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MemberSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterUserMember': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterUserMember,
          request_deserializer=member_dot_member__pb2.Member.FromString,
          response_serializer=member_dot_member__pb2.Member.SerializeToString,
      ),
      'GetMyCustomerOpenOrderList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyCustomerOpenOrderList,
          request_deserializer=member_dot_member__pb2.MyCustomerOrderRequest.FromString,
          response_serializer=member_dot_member__pb2.MyCustomerOrderReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'member.MemberSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
