# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms/sms.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sms/sms.proto',
  package='sms',
  syntax='proto3',
  serialized_pb=_b('\n\rsms/sms.proto\x12\x03sms\"\x92\x01\n\x0bSendRequest\x12\x14\n\x0cPhoneNumbers\x18\x02 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\t\x12\x0b\n\x03\x45xt\x18\x04 \x01(\t\x12\x10\n\x08SendTime\x18\x05 \x01(\t\x12\x0c\n\x04RRID\x18\x06 \x01(\t\x12\x1b\n\x06SMSISP\x18\x07 \x01(\x0e\x32\x0b.sms.SMSISP\x12\x12\n\nTemplateId\x18\x08 \x01(\x05\"5\n\x0cSendResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\x14\n\x0c\x45rrorMessage\x18\x02 \x01(\t*$\n\x06SMSISP\x12\r\n\tFunctions\x10\x00\x12\x0b\n\x07Netease\x10\x01\x32\x37\n\x06SmsSrv\x12-\n\x04Send\x12\x10.sms.SendRequest\x1a\x11.sms.SendResponse\"\x00\x42\t\xaa\x02\x06\x46M.SMSb\x06proto3')
)

_SMSISP = _descriptor.EnumDescriptor(
  name='SMSISP',
  full_name='sms.SMSISP',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Functions', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Netease', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=226,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_SMSISP)

SMSISP = enum_type_wrapper.EnumTypeWrapper(_SMSISP)
Functions = 0
Netease = 1



_SENDREQUEST = _descriptor.Descriptor(
  name='SendRequest',
  full_name='sms.SendRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PhoneNumbers', full_name='sms.SendRequest.PhoneNumbers', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Content', full_name='sms.SendRequest.Content', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ext', full_name='sms.SendRequest.Ext', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SendTime', full_name='sms.SendRequest.SendTime', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RRID', full_name='sms.SendRequest.RRID', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SMSISP', full_name='sms.SendRequest.SMSISP', index=5,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TemplateId', full_name='sms.SendRequest.TemplateId', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=169,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='sms.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Success', full_name='sms.SendResponse.Success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ErrorMessage', full_name='sms.SendResponse.ErrorMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=224,
)

_SENDREQUEST.fields_by_name['SMSISP'].enum_type = _SMSISP
DESCRIPTOR.message_types_by_name['SendRequest'] = _SENDREQUEST
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
DESCRIPTOR.enum_types_by_name['SMSISP'] = _SMSISP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendRequest = _reflection.GeneratedProtocolMessageType('SendRequest', (_message.Message,), dict(
  DESCRIPTOR = _SENDREQUEST,
  __module__ = 'sms.sms_pb2'
  # @@protoc_insertion_point(class_scope:sms.SendRequest)
  ))
_sym_db.RegisterMessage(SendRequest)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESPONSE,
  __module__ = 'sms.sms_pb2'
  # @@protoc_insertion_point(class_scope:sms.SendResponse)
  ))
_sym_db.RegisterMessage(SendResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\006FM.SMS'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SmsSrvStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Send = channel.unary_unary(
          '/sms.SmsSrv/Send',
          request_serializer=SendRequest.SerializeToString,
          response_deserializer=SendResponse.FromString,
          )


  class SmsSrvServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Send(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SmsSrvServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Send': grpc.unary_unary_rpc_method_handler(
            servicer.Send,
            request_deserializer=SendRequest.FromString,
            response_serializer=SendResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'sms.SmsSrv', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSmsSrvServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Send(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSmsSrvStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Send(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Send.future = None


  def beta_create_SmsSrv_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('sms.SmsSrv', 'Send'): SendRequest.FromString,
    }
    response_serializers = {
      ('sms.SmsSrv', 'Send'): SendResponse.SerializeToString,
    }
    method_implementations = {
      ('sms.SmsSrv', 'Send'): face_utilities.unary_unary_inline(servicer.Send),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_SmsSrv_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('sms.SmsSrv', 'Send'): SendRequest.SerializeToString,
    }
    response_deserializers = {
      ('sms.SmsSrv', 'Send'): SendResponse.FromString,
    }
    cardinalities = {
      'Send': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'sms.SmsSrv', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
