# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from csmember import member_pb2 as csmember_dot_member__pb2


class MemberSrvStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMemberExtendByMemberId = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberExtendByMemberId',
        request_serializer=csmember_dot_member__pb2.GetMemberExtendByMemberIdRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberExtendByMemberIdResponse.FromString,
        )
    self.GetMyCustomerList = channel.unary_unary(
        '/csmember.MemberSrv/GetMyCustomerList',
        request_serializer=csmember_dot_member__pb2.GetMyCustomerListRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyCustomerListResponse.FromString,
        )
    self.GetCustomerFollowUpRemarkListPage = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerFollowUpRemarkListPage',
        request_serializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkListPageRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkListPageResponse.FromString,
        )
    self.GetCustomerFollowUpRemarkModel = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerFollowUpRemarkModel',
        request_serializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkModelRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkModelResponse.FromString,
        )
    self.AddFollowUpRemark = channel.unary_unary(
        '/csmember.MemberSrv/AddFollowUpRemark',
        request_serializer=csmember_dot_member__pb2.MV2MyCustomerFollowUpDetall.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.BoolMsg.FromString,
        )
    self.GetMyMemberList = channel.unary_unary(
        '/csmember.MemberSrv/GetMyMemberList',
        request_serializer=csmember_dot_member__pb2.GetMyMemberListRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyMemberListResponse.FromString,
        )
    self.GetMyMemberCustomerList = channel.unary_unary(
        '/csmember.MemberSrv/GetMyMemberCustomerList',
        request_serializer=csmember_dot_member__pb2.GetMyMemberCustomerListRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyMemberCustomerListResponse.FromString,
        )
    self.GetMyMemberDetailByMemberID = channel.unary_unary(
        '/csmember.MemberSrv/GetMyMemberDetailByMemberID',
        request_serializer=csmember_dot_member__pb2.GetMyMemberDetailByMemberIDRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyMemberDetailByMemberIDResponse.FromString,
        )
    self.GetMemberCommissionTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionTotal',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionTotalResponse.FromString,
        )
    self.GetCustomerVolumeTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerVolumeTotal',
        request_serializer=csmember_dot_member__pb2.GetCustomerVolumeTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerVolumeTotalResponse.FromString,
        )
    self.GetCustomerVolumeTotalTop20 = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerVolumeTotalTop20',
        request_serializer=csmember_dot_member__pb2.GetCustomerVolumeTotalTop20Request.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerVolumeTotalTop20Response.FromString,
        )
    self.GetCustomerCountTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerCountTotal',
        request_serializer=csmember_dot_member__pb2.GetCustomerCountTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerCountTotalResponse.FromString,
        )
    self.GetPositionsReport = channel.unary_unary(
        '/csmember.MemberSrv/GetPositionsReport',
        request_serializer=csmember_dot_member__pb2.GetPositionsReportRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetPositionsReportResponse.FromString,
        )
    self.GetPositionsReportCommission = channel.unary_unary(
        '/csmember.MemberSrv/GetPositionsReportCommission',
        request_serializer=csmember_dot_member__pb2.GetPositionsReportCommissionRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetPositionsReportCommissionResponse.FromString,
        )
    self.GetPositionsReportCommissionTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetPositionsReportCommissionTotal',
        request_serializer=csmember_dot_member__pb2.GetPositionsReportCommissionRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.MV2PositionsReportCommission.FromString,
        )
    self.GetPositionsReportDetailOpen = channel.unary_unary(
        '/csmember.MemberSrv/GetPositionsReportDetailOpen',
        request_serializer=csmember_dot_member__pb2.GetPositionsReportDetailRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetPositionsReportDetailOpenResponse.FromString,
        )
    self.GetPositionsReportDetailClose = channel.unary_unary(
        '/csmember.MemberSrv/GetPositionsReportDetailClose',
        request_serializer=csmember_dot_member__pb2.GetPositionsReportDetailRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetPositionsReportDetailCloseResponse.FromString,
        )
    self.ClearPositionsReportCache = channel.unary_unary(
        '/csmember.MemberSrv/ClearPositionsReportCache',
        request_serializer=csmember_dot_member__pb2.ClearPositionsReportCacheRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.ClearPositionsReportCacheResponse.FromString,
        )
    self.GetMyCustomerOrdersOpenList = channel.unary_unary(
        '/csmember.MemberSrv/GetMyCustomerOrdersOpenList',
        request_serializer=csmember_dot_member__pb2.GetMyCustomerOrdersRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyCustomerOrdersOpenListResponse.FromString,
        )
    self.GetMyCustomerOrdersClosedList = channel.unary_unary(
        '/csmember.MemberSrv/GetMyCustomerOrdersClosedList',
        request_serializer=csmember_dot_member__pb2.GetMyCustomerOrdersRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyCustomerOrdersClosedListResponse.FromString,
        )
    self.GetMyCustomerOrdersTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetMyCustomerOrdersTotal',
        request_serializer=csmember_dot_member__pb2.IntMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMyCustomerOrdersTotalResponse.FromString,
        )
    self.SendUpMemberEmail = channel.unary_unary(
        '/csmember.MemberSrv/SendUpMemberEmail',
        request_serializer=csmember_dot_member__pb2.SendUpMemberEmailRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.SendUpMemberEmailResponse.FromString,
        )
    self.GetMemberCommissionApplyTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionApplyTotal',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionApplyTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionApplyTotalResponse.FromString,
        )
    self.GetMemberCommissionApplyList = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionApplyList',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionApplyListRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionApplyListResponse.FromString,
        )
    self.MemberCommissionApplyAdd = channel.unary_unary(
        '/csmember.MemberSrv/MemberCommissionApplyAdd',
        request_serializer=csmember_dot_member__pb2.MemberCommissionApplyAddRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.MemberCommissionApplyAddResponse.FromString,
        )
    self.GetMemberCommissionDetailSymbolList = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionDetailSymbolList',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionDetailSymbolListRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionDetailSymbolListResponse.FromString,
        )
    self.GetMemberCommissionDetail = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionDetail',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionDetailRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionDetailResponse.FromString,
        )
    self.GetMemberCommissionExportList = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionExportList',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionExportListRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionExportListResponse.FromString,
        )
    self.GetMemberCommissionDetailTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionDetailTotal',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionDetailTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionDetailTotalResponse.FromString,
        )
    self.GetMemberCommissionDayTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionDayTotal',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionDayTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionDayTotalResponse.FromString,
        )
    self.GetMemberCommissionMonthTotal = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberCommissionMonthTotal',
        request_serializer=csmember_dot_member__pb2.GetMemberCommissionMonthTotalRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberCommissionMonthTotalResponse.FromString,
        )
    self.RegUserMemberInfo = channel.unary_unary(
        '/csmember.MemberSrv/RegUserMemberInfo',
        request_serializer=csmember_dot_member__pb2.RegUserMemberInfoRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.RegUserMemberInfoResponse.FromString,
        )
    self.MemberRegisterAdd = channel.unary_unary(
        '/csmember.MemberSrv/MemberRegisterAdd',
        request_serializer=csmember_dot_member__pb2.MemberRegisterAddRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.MemberRegisterAddResponse.FromString,
        )
    self.MemberRegisterUpdate = channel.unary_unary(
        '/csmember.MemberSrv/MemberRegisterUpdate',
        request_serializer=csmember_dot_member__pb2.MemberRegisterUpdateRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.MemberRegisterUpdateResponse.FromString,
        )
    self.UserMemberInfoAdd = channel.unary_unary(
        '/csmember.MemberSrv/UserMemberInfoAdd',
        request_serializer=csmember_dot_member__pb2.UserMemberInfoRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.UserMemberInfoResponse.FromString,
        )
    self.UserMemberInfoUpdate = channel.unary_unary(
        '/csmember.MemberSrv/UserMemberInfoUpdate',
        request_serializer=csmember_dot_member__pb2.UserMemberInfoRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.UserMemberInfoResponse.FromString,
        )
    self.GetMemberInfoByMemberId = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberInfoByMemberId',
        request_serializer=csmember_dot_member__pb2.GetMemberInfoByMemberIdRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberInfoByMemberIdResponse.FromString,
        )
    self.GetUserInfoByUserId = channel.unary_unary(
        '/csmember.MemberSrv/GetUserInfoByUserId',
        request_serializer=csmember_dot_member__pb2.GetUserInfoByUserIdRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetUserInfoByUserIdResponse.FromString,
        )
    self.GetUserBusinessTypeByMemberId = channel.unary_unary(
        '/csmember.MemberSrv/GetUserBusinessTypeByMemberId',
        request_serializer=csmember_dot_member__pb2.GetUserBusinessTypeByMemberIdRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetUserBusinessTypeByMemberIdResponse.FromString,
        )
    self.GetMemberUserInfoByUserId = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberUserInfoByUserId',
        request_serializer=csmember_dot_member__pb2.StringMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberUserInfoByUserIdResponse.FromString,
        )
    self.GetMemberUserInfoBySelfWhere = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberUserInfoBySelfWhere',
        request_serializer=csmember_dot_member__pb2.StringMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberUserInfoBySelfWhereResponse.FromString,
        )
    self.GetUserMemberByUserId = channel.unary_unary(
        '/csmember.MemberSrv/GetUserMemberByUserId',
        request_serializer=csmember_dot_member__pb2.StringMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetUserMemberByUserIdResponse.FromString,
        )
    self.GetMemberInfoBySubDomain = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberInfoBySubDomain',
        request_serializer=csmember_dot_member__pb2.StringMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberInfoBySubDomainResponse.FromString,
        )
    self.ExistMobileOrEmailByUserID = channel.unary_unary(
        '/csmember.MemberSrv/ExistMobileOrEmailByUserID',
        request_serializer=csmember_dot_member__pb2.ExistMobileOrEmailByUserIDRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.ExistMobileOrEmailByUserIDResponse.FromString,
        )
    self.GetIsMemberInfoByDomainName = channel.unary_unary(
        '/csmember.MemberSrv/GetIsMemberInfoByDomainName',
        request_serializer=csmember_dot_member__pb2.StringMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetIsMemberInfoByDomainNameResponse.FromString,
        )
    self.GetMemberRelationShipByMemberId = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberRelationShipByMemberId',
        request_serializer=csmember_dot_member__pb2.StringMsg.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberRelationShipByMemberIdResponse.FromString,
        )
    self.GetCustomerDetailByUserId = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerDetailByUserId',
        request_serializer=csmember_dot_member__pb2.GetCustomerDetailByUserIdRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerDetailByUserIdResponse.FromString,
        )
    self.GetMemberParentNickNames = channel.unary_unary(
        '/csmember.MemberSrv/GetMemberParentNickNames',
        request_serializer=csmember_dot_member__pb2.GetMemberParentNickNamesRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetMemberParentNickNamesResponse.FromString,
        )
    self.GetCustomerParentNickNames = channel.unary_unary(
        '/csmember.MemberSrv/GetCustomerParentNickNames',
        request_serializer=csmember_dot_member__pb2.GetCustomerParentNickNamesRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetCustomerParentNickNamesResponse.FromString,
        )
    self.GetParentsNickNameToLoginMember = channel.unary_unary(
        '/csmember.MemberSrv/GetParentsNickNameToLoginMember',
        request_serializer=csmember_dot_member__pb2.GetParentsNickNameToLoginMemberRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.GetParentsNickNameToLoginMemberResponse.FromString,
        )
    self.EnableMemberExtension = channel.unary_unary(
        '/csmember.MemberSrv/EnableMemberExtension',
        request_serializer=csmember_dot_member__pb2.EnableMemberExtensionRequest.SerializeToString,
        response_deserializer=csmember_dot_member__pb2.EnableMemberExtensionResponse.FromString,
        )


class MemberSrvServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMemberExtendByMemberId(self, request, context):
    """会员管理-会员推广
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyCustomerList(self, request, context):
    """**我的直客列表**
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerFollowUpRemarkListPage(self, request, context):
    """会员管理-我的直客-客户的跟进记录，列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerFollowUpRemarkModel(self, request, context):
    """会员管理-我的直客-客户的跟进记录，实体
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddFollowUpRemark(self, request, context):
    """会员管理-我的直客-新增跟进记录
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyMemberList(self, request, context):
    """**我的会员列表**
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyMemberCustomerList(self, request, context):
    """会员管理-我的会员-直属客户
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyMemberDetailByMemberID(self, request, context):
    """会员管理-我的会员-详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionTotal(self, request, context):
    """**统计报表**

    总服务费（按天、月统计）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerVolumeTotal(self, request, context):
    """总交易量，跟随交易量（按天、月统计）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerVolumeTotalTop20(self, request, context):
    """客户交易量Top20（按天、月统计）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerCountTotal(self, request, context):
    """总客户数（按天、月统计）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPositionsReport(self, request, context):
    """**仓位总结**

    会员管理-仓位总结-主列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPositionsReportCommission(self, request, context):
    """会员管理-仓位总结-详情-服务费说明，列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPositionsReportCommissionTotal(self, request, context):
    """会员管理-仓位总结-详情-服务费说明，统计
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPositionsReportDetailOpen(self, request, context):
    """会员管理-仓位总结-详情-订单明细-正在持仓
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPositionsReportDetailClose(self, request, context):
    """会员管理-仓位总结-查看详情-历史交易
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearPositionsReportCache(self, request, context):
    """会员管理-仓位总结-清除所有仓位总结主列表缓存
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyCustomerOrdersOpenList(self, request, context):
    """**客户订单**

    会员管理-客户订单-正在持仓
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyCustomerOrdersClosedList(self, request, context):
    """会员管理-客户订单-历史交易
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMyCustomerOrdersTotal(self, request, context):
    """会员管理-客户订单-顶部Tab统计
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendUpMemberEmail(self, request, context):
    """会员服务费申请时，确认会员信息是否存在，然后新增/修改后发送邮件方法
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionApplyTotal(self, request, context):
    """**会员服务费**

    会员服务费申请顶部统计
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionApplyList(self, request, context):
    """会员管理-会员服务费申请,列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MemberCommissionApplyAdd(self, request, context):
    """会员管理-会员服务费申请
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionDetailSymbolList(self, request, context):
    """会员管理-服务费明细（交易品种列表）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionDetail(self, request, context):
    """会员管理-会员服务费-服务费明细
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionExportList(self, request, context):
    """会员管理-会员服务费-服务费明细导出列表
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionDetailTotal(self, request, context):
    """会员管理-会员服务费-顶部Tab统计
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionDayTotal(self, request, context):
    """会员管理-会员服务费-日服务费统计
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberCommissionMonthTotal(self, request, context):
    """会员管理-会员服务费-月服务费统计
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RegUserMemberInfo(self, request, context):
    """**会员公共方法**

    网站根据邀请码，即会员ID，来注册账号，注册成功，就返回新用户的实体，否则返回空实体
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MemberRegisterAdd(self, request, context):
    """新增会员信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MemberRegisterUpdate(self, request, context):
    """修改会员信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserMemberInfoAdd(self, request, context):
    """新增用户会员表信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserMemberInfoUpdate(self, request, context):
    """修改用户会员表信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberInfoByMemberId(self, request, context):
    """根据会员ID，获取会员表信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserInfoByUserId(self, request, context):
    """根据用户ID,获取U_user表，MV2_User_Member表信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserBusinessTypeByMemberId(self, request, context):
    """根据会员ID获取该会员下级用户所处业务线类型（1直客业务体系 2个人会员业务体系 3机构会员业务体系）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberUserInfoByUserId(self, request, context):
    """根据用户ID,获取用户表，会员表信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberUserInfoBySelfWhere(self, request, context):
    """根据自定义条件,获取用户表，会员表信息
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserMemberByUserId(self, request, context):
    """根据用户id获取MV2_User_Member实体对象
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberInfoBySubDomain(self, request, context):
    """根据二级域名获取MV2_MemberInfo实体对象
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ExistMobileOrEmailByUserID(self, request, context):
    """根据二级域名查询该用户是否是会员（存在：true ， 不存在：flase）
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIsMemberInfoByDomainName(self, request, context):
    """根据二级域名查询是否有该数据
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberRelationShipByMemberId(self, request, context):
    """根据会员ID获取会员上下级关系实体对象
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerDetailByUserId(self, request, context):
    """根据用户ID，经纪商ID,交易账号获取客户详情
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetMemberParentNickNames(self, request, context):
    """根据会员ID返回会员所有上级MemberId及昵称,直到指定上级。返回格式：MemberId|NickName,MemberId|NickName
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCustomerParentNickNames(self, request, context):
    """根据用户ID返回客户所有上级MemberId及昵称,直到指定上级。返回格式：MemberId|NickName,MemberId|NickName
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetParentsNickNameToLoginMember(self, request, context):
    """根据会员ID返回所有上级MemberId及昵称,直至指定上级。返回格式：NickName > NickName
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnableMemberExtension(self, request, context):
    """启用/禁用会员推广广(0禁用 1启用)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MemberSrvServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMemberExtendByMemberId': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberExtendByMemberId,
          request_deserializer=csmember_dot_member__pb2.GetMemberExtendByMemberIdRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberExtendByMemberIdResponse.SerializeToString,
      ),
      'GetMyCustomerList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyCustomerList,
          request_deserializer=csmember_dot_member__pb2.GetMyCustomerListRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyCustomerListResponse.SerializeToString,
      ),
      'GetCustomerFollowUpRemarkListPage': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerFollowUpRemarkListPage,
          request_deserializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkListPageRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkListPageResponse.SerializeToString,
      ),
      'GetCustomerFollowUpRemarkModel': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerFollowUpRemarkModel,
          request_deserializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkModelRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerFollowUpRemarkModelResponse.SerializeToString,
      ),
      'AddFollowUpRemark': grpc.unary_unary_rpc_method_handler(
          servicer.AddFollowUpRemark,
          request_deserializer=csmember_dot_member__pb2.MV2MyCustomerFollowUpDetall.FromString,
          response_serializer=csmember_dot_member__pb2.BoolMsg.SerializeToString,
      ),
      'GetMyMemberList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyMemberList,
          request_deserializer=csmember_dot_member__pb2.GetMyMemberListRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyMemberListResponse.SerializeToString,
      ),
      'GetMyMemberCustomerList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyMemberCustomerList,
          request_deserializer=csmember_dot_member__pb2.GetMyMemberCustomerListRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyMemberCustomerListResponse.SerializeToString,
      ),
      'GetMyMemberDetailByMemberID': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyMemberDetailByMemberID,
          request_deserializer=csmember_dot_member__pb2.GetMyMemberDetailByMemberIDRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyMemberDetailByMemberIDResponse.SerializeToString,
      ),
      'GetMemberCommissionTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionTotal,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionTotalResponse.SerializeToString,
      ),
      'GetCustomerVolumeTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerVolumeTotal,
          request_deserializer=csmember_dot_member__pb2.GetCustomerVolumeTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerVolumeTotalResponse.SerializeToString,
      ),
      'GetCustomerVolumeTotalTop20': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerVolumeTotalTop20,
          request_deserializer=csmember_dot_member__pb2.GetCustomerVolumeTotalTop20Request.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerVolumeTotalTop20Response.SerializeToString,
      ),
      'GetCustomerCountTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerCountTotal,
          request_deserializer=csmember_dot_member__pb2.GetCustomerCountTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerCountTotalResponse.SerializeToString,
      ),
      'GetPositionsReport': grpc.unary_unary_rpc_method_handler(
          servicer.GetPositionsReport,
          request_deserializer=csmember_dot_member__pb2.GetPositionsReportRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetPositionsReportResponse.SerializeToString,
      ),
      'GetPositionsReportCommission': grpc.unary_unary_rpc_method_handler(
          servicer.GetPositionsReportCommission,
          request_deserializer=csmember_dot_member__pb2.GetPositionsReportCommissionRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetPositionsReportCommissionResponse.SerializeToString,
      ),
      'GetPositionsReportCommissionTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetPositionsReportCommissionTotal,
          request_deserializer=csmember_dot_member__pb2.GetPositionsReportCommissionRequest.FromString,
          response_serializer=csmember_dot_member__pb2.MV2PositionsReportCommission.SerializeToString,
      ),
      'GetPositionsReportDetailOpen': grpc.unary_unary_rpc_method_handler(
          servicer.GetPositionsReportDetailOpen,
          request_deserializer=csmember_dot_member__pb2.GetPositionsReportDetailRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetPositionsReportDetailOpenResponse.SerializeToString,
      ),
      'GetPositionsReportDetailClose': grpc.unary_unary_rpc_method_handler(
          servicer.GetPositionsReportDetailClose,
          request_deserializer=csmember_dot_member__pb2.GetPositionsReportDetailRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetPositionsReportDetailCloseResponse.SerializeToString,
      ),
      'ClearPositionsReportCache': grpc.unary_unary_rpc_method_handler(
          servicer.ClearPositionsReportCache,
          request_deserializer=csmember_dot_member__pb2.ClearPositionsReportCacheRequest.FromString,
          response_serializer=csmember_dot_member__pb2.ClearPositionsReportCacheResponse.SerializeToString,
      ),
      'GetMyCustomerOrdersOpenList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyCustomerOrdersOpenList,
          request_deserializer=csmember_dot_member__pb2.GetMyCustomerOrdersRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyCustomerOrdersOpenListResponse.SerializeToString,
      ),
      'GetMyCustomerOrdersClosedList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyCustomerOrdersClosedList,
          request_deserializer=csmember_dot_member__pb2.GetMyCustomerOrdersRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyCustomerOrdersClosedListResponse.SerializeToString,
      ),
      'GetMyCustomerOrdersTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyCustomerOrdersTotal,
          request_deserializer=csmember_dot_member__pb2.IntMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetMyCustomerOrdersTotalResponse.SerializeToString,
      ),
      'SendUpMemberEmail': grpc.unary_unary_rpc_method_handler(
          servicer.SendUpMemberEmail,
          request_deserializer=csmember_dot_member__pb2.SendUpMemberEmailRequest.FromString,
          response_serializer=csmember_dot_member__pb2.SendUpMemberEmailResponse.SerializeToString,
      ),
      'GetMemberCommissionApplyTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionApplyTotal,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionApplyTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionApplyTotalResponse.SerializeToString,
      ),
      'GetMemberCommissionApplyList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionApplyList,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionApplyListRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionApplyListResponse.SerializeToString,
      ),
      'MemberCommissionApplyAdd': grpc.unary_unary_rpc_method_handler(
          servicer.MemberCommissionApplyAdd,
          request_deserializer=csmember_dot_member__pb2.MemberCommissionApplyAddRequest.FromString,
          response_serializer=csmember_dot_member__pb2.MemberCommissionApplyAddResponse.SerializeToString,
      ),
      'GetMemberCommissionDetailSymbolList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionDetailSymbolList,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionDetailSymbolListRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionDetailSymbolListResponse.SerializeToString,
      ),
      'GetMemberCommissionDetail': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionDetail,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionDetailRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionDetailResponse.SerializeToString,
      ),
      'GetMemberCommissionExportList': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionExportList,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionExportListRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionExportListResponse.SerializeToString,
      ),
      'GetMemberCommissionDetailTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionDetailTotal,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionDetailTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionDetailTotalResponse.SerializeToString,
      ),
      'GetMemberCommissionDayTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionDayTotal,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionDayTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionDayTotalResponse.SerializeToString,
      ),
      'GetMemberCommissionMonthTotal': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberCommissionMonthTotal,
          request_deserializer=csmember_dot_member__pb2.GetMemberCommissionMonthTotalRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberCommissionMonthTotalResponse.SerializeToString,
      ),
      'RegUserMemberInfo': grpc.unary_unary_rpc_method_handler(
          servicer.RegUserMemberInfo,
          request_deserializer=csmember_dot_member__pb2.RegUserMemberInfoRequest.FromString,
          response_serializer=csmember_dot_member__pb2.RegUserMemberInfoResponse.SerializeToString,
      ),
      'MemberRegisterAdd': grpc.unary_unary_rpc_method_handler(
          servicer.MemberRegisterAdd,
          request_deserializer=csmember_dot_member__pb2.MemberRegisterAddRequest.FromString,
          response_serializer=csmember_dot_member__pb2.MemberRegisterAddResponse.SerializeToString,
      ),
      'MemberRegisterUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.MemberRegisterUpdate,
          request_deserializer=csmember_dot_member__pb2.MemberRegisterUpdateRequest.FromString,
          response_serializer=csmember_dot_member__pb2.MemberRegisterUpdateResponse.SerializeToString,
      ),
      'UserMemberInfoAdd': grpc.unary_unary_rpc_method_handler(
          servicer.UserMemberInfoAdd,
          request_deserializer=csmember_dot_member__pb2.UserMemberInfoRequest.FromString,
          response_serializer=csmember_dot_member__pb2.UserMemberInfoResponse.SerializeToString,
      ),
      'UserMemberInfoUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.UserMemberInfoUpdate,
          request_deserializer=csmember_dot_member__pb2.UserMemberInfoRequest.FromString,
          response_serializer=csmember_dot_member__pb2.UserMemberInfoResponse.SerializeToString,
      ),
      'GetMemberInfoByMemberId': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberInfoByMemberId,
          request_deserializer=csmember_dot_member__pb2.GetMemberInfoByMemberIdRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberInfoByMemberIdResponse.SerializeToString,
      ),
      'GetUserInfoByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserInfoByUserId,
          request_deserializer=csmember_dot_member__pb2.GetUserInfoByUserIdRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetUserInfoByUserIdResponse.SerializeToString,
      ),
      'GetUserBusinessTypeByMemberId': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserBusinessTypeByMemberId,
          request_deserializer=csmember_dot_member__pb2.GetUserBusinessTypeByMemberIdRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetUserBusinessTypeByMemberIdResponse.SerializeToString,
      ),
      'GetMemberUserInfoByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberUserInfoByUserId,
          request_deserializer=csmember_dot_member__pb2.StringMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberUserInfoByUserIdResponse.SerializeToString,
      ),
      'GetMemberUserInfoBySelfWhere': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberUserInfoBySelfWhere,
          request_deserializer=csmember_dot_member__pb2.StringMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberUserInfoBySelfWhereResponse.SerializeToString,
      ),
      'GetUserMemberByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserMemberByUserId,
          request_deserializer=csmember_dot_member__pb2.StringMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetUserMemberByUserIdResponse.SerializeToString,
      ),
      'GetMemberInfoBySubDomain': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberInfoBySubDomain,
          request_deserializer=csmember_dot_member__pb2.StringMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberInfoBySubDomainResponse.SerializeToString,
      ),
      'ExistMobileOrEmailByUserID': grpc.unary_unary_rpc_method_handler(
          servicer.ExistMobileOrEmailByUserID,
          request_deserializer=csmember_dot_member__pb2.ExistMobileOrEmailByUserIDRequest.FromString,
          response_serializer=csmember_dot_member__pb2.ExistMobileOrEmailByUserIDResponse.SerializeToString,
      ),
      'GetIsMemberInfoByDomainName': grpc.unary_unary_rpc_method_handler(
          servicer.GetIsMemberInfoByDomainName,
          request_deserializer=csmember_dot_member__pb2.StringMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetIsMemberInfoByDomainNameResponse.SerializeToString,
      ),
      'GetMemberRelationShipByMemberId': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberRelationShipByMemberId,
          request_deserializer=csmember_dot_member__pb2.StringMsg.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberRelationShipByMemberIdResponse.SerializeToString,
      ),
      'GetCustomerDetailByUserId': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerDetailByUserId,
          request_deserializer=csmember_dot_member__pb2.GetCustomerDetailByUserIdRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerDetailByUserIdResponse.SerializeToString,
      ),
      'GetMemberParentNickNames': grpc.unary_unary_rpc_method_handler(
          servicer.GetMemberParentNickNames,
          request_deserializer=csmember_dot_member__pb2.GetMemberParentNickNamesRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetMemberParentNickNamesResponse.SerializeToString,
      ),
      'GetCustomerParentNickNames': grpc.unary_unary_rpc_method_handler(
          servicer.GetCustomerParentNickNames,
          request_deserializer=csmember_dot_member__pb2.GetCustomerParentNickNamesRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetCustomerParentNickNamesResponse.SerializeToString,
      ),
      'GetParentsNickNameToLoginMember': grpc.unary_unary_rpc_method_handler(
          servicer.GetParentsNickNameToLoginMember,
          request_deserializer=csmember_dot_member__pb2.GetParentsNickNameToLoginMemberRequest.FromString,
          response_serializer=csmember_dot_member__pb2.GetParentsNickNameToLoginMemberResponse.SerializeToString,
      ),
      'EnableMemberExtension': grpc.unary_unary_rpc_method_handler(
          servicer.EnableMemberExtension,
          request_deserializer=csmember_dot_member__pb2.EnableMemberExtensionRequest.FromString,
          response_serializer=csmember_dot_member__pb2.EnableMemberExtensionResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'csmember.MemberSrv', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
